// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3whF1Zrc3V8OSym1IG8GDJTS3GcdtXUk',
    appId: '1:968947313570:web:568f6adde673227ada20fb',
    messagingSenderId: '968947313570',
    projectId: 'suwon-mate',
    authDomain: 'suwon-mate.firebaseapp.com',
    databaseURL: 'https://suwon-mate-default-rtdb.firebaseio.com',
    storageBucket: 'suwon-mate.appspot.com',
    measurementId: 'G-5HP3CQK0B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYyJfHSgWE6qIgeyvnBsGvbZvJt6IYybg',
    appId: '1:968947313570:android:651e7c8fe170276dda20fb',
    messagingSenderId: '968947313570',
    projectId: 'suwon-mate',
    databaseURL: 'https://suwon-mate-default-rtdb.firebaseio.com',
    storageBucket: 'suwon-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmnnzYmVLBq5sBPmRAzEmoCWv_2V1zac',
    appId: '1:968947313570:ios:abbe022cc79774b3da20fb',
    messagingSenderId: '968947313570',
    projectId: 'suwon-mate',
    databaseURL: 'https://suwon-mate-default-rtdb.firebaseio.com',
    storageBucket: 'suwon-mate.appspot.com',
    iosClientId: '968947313570-73t21aa5ksq3acvpc7o9dp67nqea01hm.apps.googleusercontent.com',
    iosBundleId: 'com.sn30.suwonuniv.info.suwonMate',
  );
}
