name: Flutter build & Deploy

on:
  push:
    branches: [ main, next ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0

      - name: Install dependency
        run: flutter pub get

      - name: Build Web App
        run: flutter build web

      - name: Upload code
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: |
            build/web/
            firebase.json
            staticwebapp.config.json
            .firebaserc

  firebase-deploy-main:
    name: Deploy to Firebase(Live)
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code

      - name: Firebase Hosting Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUWON_MATE }}'
          channelId: live
          projectId: suwon-mate

  firebase-deploy-next:
    name: Deploy to Firebase(Preview)
    if: github.ref_name == 'next'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code

      - name: Firebase Hosting Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUWON_MATE }}'
          channelId: next
          projectId: suwon-mate