name: Flutter build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  BuildAPK:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependency
        run: flutter pub get

      - name: Build Android App
        run: flutter build apk

      - name: rename .apk file
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/suwon_mate_android.apk

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            build/app/outputs/flutter-apk/suwon_mate_android.apk

  BuildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependency
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Zip Output File
        run: Compress-Archive -Path build\windows\runner\Release -DestinationPath suwon_mate_win.zip

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            suwon_mate_win.zip
  
  BuildmacOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependency
        run: flutter pub get

      - name: Configuration to build macOS App
        run: flutter config --enable-macos-desktop

      - name: Build macOS App
        run: flutter build macos

      - name: Zip .app file
        run:  cd build/macos/Build/Products/Release && zip -rD suwon_mate.app.zip suwon_mate.app

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            suwon_mate.app.zip

  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependency
        run: flutter pub get

      - name: Setting build Envirionment
        run: |
          sudo apt update -y
          sudo apt install -y cmake ninja-build libgtk-3-dev

      - name: Configuration to build Linux App
        run: |
          flutter config --enable-linux-desktop
          flutter create .

      - name: Build Linux App
        run: flutter build linux

      - name: Zip output files
        run: cd build/linux/x64/release && zip -rD suwon_mate_linux.zip bundle

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            suwon_mate_linux.zip

  Release:
    runs-on: ubuntu-latest
    needs: [BuildWindows,BuildAPK,BuildmacOS,BuildLinux]
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: output
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            suwon_mate_android.apk
            suwon_mate_win.zip
            suwon_mate.app.zip
            suwon_mate_linux.zip

  AlertNewVersion:
    runs-on: ubuntu-latest
    needs: Release
    steps:
      - name: Firebase Trigger
        uses: w9jds/firebase-trigger@v1.0.1
        with:
          credentials: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUWON_MATE }}
          databaseUrl: https://suwon-mate-default-rtdb.firebaseio.com/
          path: version/app_ver
          value: v2.0.0
