name: Flutter build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  BuildAPK:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependency
        run: flutter pub get

      - name: Build Android App
        run: flutter build apk

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            build/app/outputs/flutter-apk/app-release.apk

  BuildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependency
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Change Output File Name
        run: Rename-Item -Path build\windows\runner\Release -NewName Windows_Release

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            build\windows\runner\Windows_Release
  
  BuildmacOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependency
        run: flutter pub get

      - name: Configuration to build macOS App
        run: flutter config --enable-macos-desktop

      - name: Build macOS App
        run: flutter build macos

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            build/macos/Build/Products/Release/suwon_mate

  Release:
    runs-on: ubuntu-latest
    needs: [BuildWindows,BuildAPK,BuildmacOS]
    steps:
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: output
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release.apk
            Windows_Release
            suwon_mate
