name: Flutter build & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependancy
        run: flutter pub get

      - name: Build Web App
        run: flutter build web


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: upload
          # Directory location of the application source code
          app_location: build/web
          # Required token
          azure_static_web_apps_api_token: '${{ secrets.AZURE_STATIC_DEPLOY_TOKEN }}'
          # Directory location of the compiled application code after building
          output_location: build/web
          # Skips the build step for the application source code if set to true.
          skip_app_build: true

        - name: Firebase Hosting Deploy
          uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUWON_MATE }}'
            projectId: suwon-mate