name: Flutter build & Deploy

on:
  push:
    branches: [ web ]
  pull_request:
    branches: [ web ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0

      - name: Install dependancy
        run: flutter pub get

      - name: Build Web App
        run: flutter build web

      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: |
            build/web/
            firebase.json
            staticwebapp.config.json
            .firebaserc
          


  AzureDeploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: upload
          # Directory location of the application source code
          app_location: build/web
          # Required token
          azure_static_web_apps_api_token: '${{ secrets.AZURE_STATIC_DEPLOY_TOKEN }}'
          # Directory location of the compiled application code after building
          output_location: build/web
          # Skips the build step for the application source code if set to true.
          skip_app_build: true

  FirebaseDeploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code

      - name: Firebase Hosting Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUWON_MATE }}'
          channelId: live
          projectId: suwon-mate